### ISSUE TITLE
Android: installreferrer-1.0.aar is referenced instead of nuget Xamarin.Android.Binding.InstallReferrer

### ISSUE THREAD

**Issue by thisisthekap** [adjust/xamarin_sdk#32]
May lead to the build error given below when the adjust sdk is referenced side by side with another nuget which depends on `Xamarin.Android.Binding.InstallReferrer`:

`Xamarin.Android.Common.targets(1456, 3): [XA4215] The Java type mono.com.android.installreferrer.api.InstallReferrerStateListenerImplementor is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.`

**Comment by thisisthekap** [comment]
As @uerceg stated in PR #33, this issue is not going to be fixed any time soon.

**Comment by uerceg** [comment]
Will close this ticket for time being and reopen it once we revisit it. Nevertheless thank you for your engagement on this topic! Beyond any doubt it is nice idea to have things decoupled and we will definitely try to go down this road in next major SDK update, but due to reasons mentioned in PR comments, we can't commit to it right now. Cheers!
